### ISSUE TITLE
Label to mark where to add the daily entries

### ISSUE THREAD

**Issue by eclemens** [jb--/dailytodo#1]
Thank you for this extension, I find it very useful. I like its simplicity but still I would like to add a suggestion.

It would be nice to have a label to be able to mark from where we want to start adding the daily entries. This way I could have at the beginning of my diary some description, instructions or timeless tasks.

**Comment by jb--** [comment]
Ha! Amazing that people are using it! :) I totally did not expect that. I'd be delighted to bring in your idea.

At the moment, there is an entire document that is marked as a diary and the new entries always start on line 3. I see that this is a limitation that is not needed. 

@eclemens - what would be your take on e.g. `<!-- DAILY-TODO-LIST -->` comment, under which we would add the daily elements right away. Would that be useful for you? Any suggestions on alternative names?

**Comment by eclemens** [comment]
Amazing, that label seems perfect to me. It does its job and follows the pattern used by the other tag.

Thank you very much!
